##START,aws_rds_cluster
resource "aws_rds_cluster" "launch-database-1h67dy5iovuyd-aurora-auroracluster-o3vjahxjyyzm" {
  allocated_storage                     = 1
  allow_major_version_upgrade           = null
  apply_immediately                     = null
  availability_zones                    = ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
  backtrack_window                      = 0
  backup_retention_period               = 1
  ca_certificate_identifier             = null
  cluster_identifier                    = "launch-database-1h67dy5iovuyd-aurora-auroracluster-o3vjahxjyyzm"
  cluster_identifier_prefix             = null
  cluster_members                       = ["mdadb"]
  copy_tags_to_snapshot                 = false
  database_name                         = "mdacluster"
  db_cluster_instance_class             = null
  db_cluster_parameter_group_name       = aws_rds_cluster_parameter_group.launch-database-1h67dy5iovuyd-aurorastack-1dyk9y8asq36q-auroraclusterparametergroup-ys5paj33fdil.id
  db_instance_parameter_group_name      = null
  db_subnet_group_name                  = aws_db_subnet_group.launch-database-1h67dy5iovuyd-aurorastack-1dyk9y8asq36q-auroradbsubnetgroup-hacuv4pexwa1.id
  db_system_id                          = null
  delete_automated_backups              = true
  deletion_protection                   = false
  domain                                = null
  domain_iam_role_name                  = null
  enable_global_write_forwarding        = null
  enable_http_endpoint                  = false
  enable_local_write_forwarding         = null
  enabled_cloudwatch_logs_exports       = []
  engine                                = "aurora-postgresql"
  engine_lifecycle_support              = "open-source-rds-extended-support"
  engine_mode                           = "provisioned"
  engine_version                        = jsonencode(13.9)
  final_snapshot_identifier             = null
  global_cluster_identifier             = null
  iam_database_authentication_enabled   = false
  iam_roles                             = [aws_iam_role.RDSImportExecutionRole.arn]
  iops                                  = 0
  manage_master_user_password           = null
  master_password                       = null # sensitive
  master_user_secret_kms_key_id         = null
  master_username                       = "mdauser"
  network_type                          = "IPV4"
  performance_insights_enabled          = false
  performance_insights_kms_key_id       = null
  performance_insights_retention_period = 0
  port                                  = 3306
  preferred_backup_window               = "04:45-05:15"
  preferred_maintenance_window          = "sun:03:47-sun:04:17"
  replication_source_identifier         = null
  skip_final_snapshot                   = true
  snapshot_identifier                   = null
  source_region                         = null
  storage_encrypted                     = false
  storage_type                          = null
  tags                                  = {}
  tags_all                              = {}
  vpc_security_group_ids                = [aws_security_group.sg-073e9a2702bb17464.id]
}
