##START,aws_db_instance
resource "aws_db_instance" "mdadb" {
  allocated_storage                     = 1
  allow_major_version_upgrade           = null
  apply_immediately                     = null
  auto_minor_version_upgrade            = true
  availability_zone                     = format("%sb", data.aws_region.current.name)
  backup_retention_period               = 1
  backup_target                         = "region"
  backup_window                         = "04:45-05:15"
  ca_cert_identifier                    = "rds-ca-rsa2048-g1"
  character_set_name                    = null
  copy_tags_to_snapshot                 = false
  custom_iam_instance_profile           = null
  customer_owned_ip_enabled             = false
  db_name                               = "mdacluster"
  db_subnet_group_name                  = aws_db_subnet_group.launch-database-1h67dy5iovuyd-aurorastack-1dyk9y8asq36q-auroradbsubnetgroup-hacuv4pexwa1.id
  dedicated_log_volume                  = false
  delete_automated_backups              = true
  deletion_protection                   = false
  domain                                = null
  domain_auth_secret_arn                = null
  domain_fqdn                           = null
  domain_iam_role_name                  = null
  domain_ou                             = null
  enabled_cloudwatch_logs_exports       = []
  engine                                = "aurora-postgresql"
  engine_lifecycle_support              = "open-source-rds-extended-support"
  engine_version                        = jsonencode(13.9)
  final_snapshot_identifier             = null
  iam_database_authentication_enabled   = false
  identifier                            = "mdadb"
  identifier_prefix                     = null
  instance_class                        = "db.t4g.medium"
  iops                                  = 0
  license_model                         = "postgresql-license"
  maintenance_window                    = "fri:22:27-fri:22:57"
  manage_master_user_password           = null
  master_user_secret_kms_key_id         = null
  max_allocated_storage                 = 0
  monitoring_interval                   = 0
  monitoring_role_arn                   = null
  multi_az                              = false
  nchar_character_set_name              = null
  network_type                          = "IPV4"
  option_group_name                     = "default:aurora-postgresql-13"
  parameter_group_name                  = "default.aurora-postgresql13"
  password                              = null # sensitive
  performance_insights_enabled          = false
  performance_insights_kms_key_id       = null
  performance_insights_retention_period = 0
  port                                  = 3306
  publicly_accessible                   = false
  replica_mode                          = null
  replicate_source_db                   = null
  skip_final_snapshot                   = true
  snapshot_identifier                   = null
  storage_encrypted                     = false
  storage_throughput                    = 0
  storage_type                          = "aurora"
  tags = {
    Application = "Aurora DB"
  }
  tags_all = {
    Application = "Aurora DB"
  }
  timezone               = null
  upgrade_storage_config = null
  username               = "mdauser"
  vpc_security_group_ids = [aws_security_group.sg-073e9a2702bb17464.id]
}
